# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS

GMAIL_USERNAME: ryan.amburgy@gmail.com
GMAIL_PASSWORD: gsnkqdnuvjvrkcrn
ADMIN_NAME: Ryan Admin
ADMIN_EMAIL: ryan.amburgy@gmail.com
ADMIN_PASSWORD: secretpassword
ROLES: [admin, user, VIP]